- app/scripts/directives/switchcell.html
resolve issue [#59](https://github.com/contactless/homeui/issues/59)
readonly переключатели при отображении на больших экранах (с боковым меню) теперь отображаются с кружками контрола, как и при разрешении < 786px, на мобильных устройствах
> fix styles for readonly switch

- app/views/devices.html
resolve issue [#58](https://github.com/contactless/homeui/issues/58)
popup с текстом вида 
> 'wb-map12h_91/Voltage angle L1' value copied to clipboard
появляется только при клике на поле в виджете devices и исчезает чрез 0.5 секунды
> donWB#58-change_devices_popup_behavior

- app/scripts/directives/textcell.js
resolve issue [#66](https://github.com/contactless/homeui/issues/66)
В `displayCell` для отображения значения при `displayType = text` или значения неизвестного типа используется `textcell`.
В этом компоненте добавил отображение значения текстом если cell readonly, или input'ом, если нет
> WB#66-text_cells_value

- app/scripts/controllers/devicesController.js
- app/scripts/controllers/webUiController.js
- app/scripts/directives/displaycell.html
- app/scripts/directives/displaycell.js
- app/scripts/directives/rangecell.html
- app/scripts/directives/textcell.html
- app/scripts/directives/textcell.js
- app/scripts/directives/valuecell.html
- app/styles/css/new.css
- app/views/devices.html
resolve issue [#75](https://github.com/contactless/homeui/issues/75)
Изменил поведение копирования значений при клике на значение `displaycell` в `devices`
При клике на название канала копируется название и всплывает уведомление о копировании.
При клике на значение копируется значение и всплывает уведомление о копировании для
+ value-cell
+ text-cell
+ range-cell
> WB#75-improved_devices_values_copying

- app/index.ejs
- app/scripts/app.routes.js
- app/scripts/controllers/devicesController.js
- app/scripts/controllers/scriptController.js
- app/scripts/directives/displaycell.js
- app/styles/css/new.css
- app/views/scripts.html
- app/views/widgets.html
resolve issue #91 
Для того, что-бы при открытии адресов  _scripts/new_ и _scripts/abc.js_ раздел меню scripts выделялся как активных, была добавлена иерархическая структура в объявление роутинга.
Такое-же поведение было у раздела history - _/history/deviceId/cellId/-/-_ не выделял раздел меню history как активный. Так-же исправлено.
+ Исправлен стиль раздела меню help, когда он активный - это добавило ему белую стрелочку, когда раздел выбран.
+ Добавил белую стрелочку к выбранным элементам меню второй вложенности:
> WB#91_fix-nav-bar-active-items

- app/scripts/directives/rangecell.js
resolve issue #104
Установил watcher на значение rangecell и в нём обновляю константу, выступающую моделью для ползунка, а не один раз при инициализации как раньше. 
Для проверки есть виртуальное устройство "range-test-device" с заголовком *Вирт. уст-во для теста range*, описано в правиле `test-chane-range-value.js`, при переключении свича в котором изменяется значение.
> WB#104_range-control-fix

- app/scripts/directives/svgScheme.js
resolve issue #95
Были проблемы с тем, что из-за неверного места установки атрибута `svg-compiled-element` создавалось много лишних вложенных scop'ов с одинаковыми ключами. Добавил в scope директивы `svgCompiledElementDirective` данные из родительского scope что-бы можно было использовать баиндинг вида `ADC 5V out = {{devicedata.proxy('wb-adc/5Vout').value}} V` в тегах с директивой `svgCompiledElementDirective`
> WB#95_SVG-dashboards-fix

- Makefile
- app/scripts/app.routes.js
- package.json
- webpack.config.js
resolve issue #92 
Добавил обработку template 'ов через [ngtemplate-loader](https://github.com/WearyMonkey/ngtemplate-loader).
Этот loader при каждой сборке приложения webpack'ом регистрирует template'ы в `angular $templateCache`. Таким образом актуальные template'ы всегда есть на стороне пользователя в `main.[content-hash].js` сборке, у которой есть content-hash в имени файла, что гарантирует актуальность отдаваемых nginx'ом данных.
Т.к. templat'ы теперь хранятся в сборке из webpack и make файлов были удалены строчки с перекладыванием `views` папки.
> WB#92_ng-template-loader

- app/scripts/controllers/devicesController.js
- app/scripts/services/devicedata.js
- app/scripts/services/mqttService.js
- app/styles/css/new.css
- app/views/devices.html
- debian/changelog
remove mqtt.publish method because Paho.MQTT.Client does not contain it
improve deleting of the device
improve deleting of the device
delete optional comments
Revert "remove mqtt.publish method because Paho.MQTT.Client does not contain it"
This reverts commit 60f55008a6a74f6df3b2daeb0ecfa111e81529d4.
move all subscription handlers to one callback
move last handler & add en comments
returned automatically renamed function names
device deleting
up deb ver
> add device delete btn that call mqtt.send method for all device topics

- convert_config_v1v2.py
- debian/changelog
Some widget descriptions in dashboard can contain 'undefined' in topic name. Script will take topic name from root widget description.
> Error during dicts merge is fixed

- convert_config_v1v2.py
- debian/changelog
The fix handles the behavior when there are /config/# topics but they are not from old wb-mqtt-homeui
> Error in config conversion from v1.x is fixed.

- app/styles/main.css
- debian/changelog
Rebase of https://github.com/wirenboard/homeui/pull/193
> SVG resizing in dashboard editor is fixed

- app/scripts/components/svgEditor/view/svgView.controller.js
- debian/changelog
Rebase of https://github.com/wirenboard/homeui/pull/202
> Allow read binding to SVG text without nested tspan

- app/scripts/app.js
- app/scripts/app.routes.js
- app/scripts/controllers/devicesController.js
- app/scripts/controllers/historyController.js
- app/scripts/controllers/widgetsController.js
- app/scripts/directives/displaycell.js
- app/scripts/services/historyUrl.js
- app/styles/css/new.css
- app/views/history.html
- app/views/widgets.html
- debian/changelog
- package.json
- webpack.config.js
Rebase of https://github.com/wirenboard/homeui/pull/215
* Widget ids are now stored in url for transfering between page reloads. So it is possible to correctly show widget names in chart's legend and control's comboboxes.
* History params are stored in JSON and are packed using LZString. Resulting string is appended to url.
> Widget names are preserved in charts legend

- app/scripts/directives/widget.html
- debian/changelog
Rebase of https://github.com/wirenboard/homeui/pull/239
> Control type filter in widget's properties dialog is restored

- Makefile
It fixes build after Github banned unauthenticated access via git:// protocol which is used by one of countless Node.js modules here.
This fix should be removed in future after switching to newer dependencies versions.
> build: fix 'The unauthenticated git protocol' error

- app/scripts/services/devicedata.js
- debian/changelog
A disconnection from MQTT broker after receiving null in control's meta topic is fixed.
> Control's meta topic handling error is fixed

- app/scripts/components/json-editor/angular-json-editor.js
- app/scripts/components/json-editor/group-editor.js
- app/scripts/components/json-editor/select-with-hidden-items.js
- app/styles/main.css
- debian/changelog
При смене значения параметра другие, ранее установленные параметры на соседних вкладках могут выйти за разрешённые границы. Сделал так, чтобы такие параметры подсвечивались ошибкой. Также добавил подсветку вкладок с невалидными параметрами. Конфиг сохранять с такими ошибками теперь нельзя.
> Highlighting of tabs with invalid parameters in device config

- app/styles/main.css
- debian/changelog
описание виджетов странно ресайзилось и вылезало за границы
> css: fix widget's description resize & bounds

- app/scripts/components/json-editor/group-editor.js
- debian/changelog
Rebase of https://github.com/wirenboard/homeui/pull/340
Выделил только то, что с ошибкой связано. Изменения в шаблонизаторе отдельно сделаю, возможно, они уже не актуальны.
> Displaying of oneOf parameters by groups editor is fixed

- app/scripts/components/json-editor/group-editor.js
- debian/changelog
wb-multiple editor has item groups for select. They are defined as an array of strings in options.wb.groups. Device config editor has also groups defined in options.wb.groups. They are used for tabs and panels and defined as array of objects. json-editor merges these options if groups editor is used in oneOf array in wb-multiple. So groups editor can receive groups of wb-multiple. Ignore them.
Баг проявляется, если выбрать wbio-ai-dv-12 в настройках wb-mqtt-serial. Веб-интерфейс зависнет.
> Fix interface slowdown

- app/scripts/components/json-editor/collapsible-multiple-editor.js
- debian/changelog
Было
Стало
Всё из-за неявного преобразования 0 в false
> Fix BAC-6000 error messages display

- app/scripts/components/json-editor/disabled-editor-wrapper.js
- debian/changelog
Use options.inputAttributes.placeholder for disabled text of optional parameters
Раньше было захардкожено так
Сейчас можно в схеме задать текст
> Add ability to set disabled optional parameter text

- app/scripts/components/json-editor/wb-array-editor.js
- debian/changelog
В редакторе wb-array можно указать параметр, по которому сортировать элементы. После добавления нового элемента, производится поиск позиции, в которую его переместить. Создаётся всегда в конце массива. Если перемещать никуда не надо, то неверно находился индекс вкладки, которую надо активировать.
> Fix wb-array items creation with sorting enabled

- Makefile
sbuild резонно ругался на то, что при использовании `git config --global` записывался файл в `$HOME`, который в сборочной среде не должен использоваться, поэтому в `$HOME` было записано значение `/sbuild-nonexistent`. В старых версиях `sbuild`, видимо, эта директория всё же создавалась. В bullseye теперь её нет (и это правильное поведение: https://lists.debian.org/debian-devel/2016/02/msg00455.html).
Починил makefile так, чтобы конфиг применялся только в рамках репозитория.
> fix build on bullseye

- app/views/help.html
- debian/changelog
В #360 упущен `| translate`, без него оказывается не работает.
> Fix docs url

- app/scripts/components/json-editor/group-editor.js
- debian/changelog
При установке значения в редактор, я делал вначале один шаг определения какие параметры надо показывать. В результате последующая полная процедура останавливалась сразу на первом шаге, т.к. не было изменений в отображаемых параметрах. Убрал этот один шаг, т.к. ниже по коду делается полная процедура определения того, что надо отображать.
При редактировании MAI6 получалась такая картина, а должно было быть как внизу
> Fix displaying of conditional config parameters

- app/scripts/components/json-editor/wb-array-editor.js
- app/styles/main.css
- debian/changelog
The dialog can be canceled by clicking outside of it
> Remove "Cancel" button from create item dialog in wb-array

- debian/changelog
- debian/control
homeui doesn't build with nodejs 16.x.
This fix temporarily forces nodejs to be 12.x (as in Debian bullseye upstream).
> debian: forbid nodejs>12.x as build-dependency

- README.md
- app/scripts/app.js
- app/scripts/controllers/webUiController.js
- debian/changelog
Как воспроизвести:
1. Очистить localStorage для UI
2. Настроить в браузере Preffered Languages, где первым в списке будет любой язык кроме ru и en, вторым ru
3. Обновить, UI отобразится на английском, хотя учитывая список языков, по приоритету должен быть выбран второй (русский)
> Support preffered languages settings

- debian/changelog
- webpack.config.js
Сейчас:
```sh
$ find /var/www -name "*..*"
/var/www/fontawesome-webfont..svg
/var/www/fa-solid-900..ttf
/var/www/fontawesome-webfont..woff
/var/www/fa-solid-900..woff
/var/www/glyphicons-halflings-regular..svg
/var/www/fa-solid-900..woff2
/var/www/fontawesome-webfont..ttf
/var/www/fa-solid-900..svg
/var/www/glyphicons-halflings-regular..woff
/var/www/glyphicons-halflings-regular..ttf
```
> Fix font assets file names

- debian/changelog
- package.json
- webpack.config.js
Add support for HTML format in titles/headers and descriptions in json-editor generated forms
Теперь в названиях и описаниях параметров json-editor'а можно использовать HTML тэги, SVG и MathML
```
Для детектирования нажатий значение должно быть в <b>5-10</b> раз меньше,<br>чем время ожидания второго нажатия. На прошивках до 1.19.0 максимально возможное время 250 мс
```
> Add support for HTML format labels in config editor

- app/scripts/controllers/historyController.js
- debian/changelog
> Fix plot hover label on History page

- app/scripts/services/mqttService.js
Hello, currently, if you try to use reverse proxy with SSL, you will face the issue that HomeUI will still try to use a WS connection over the HTTPS-served page to establish MQTT connection. Such behavior will cause the following error.
```
Mixed Content: The page at 'https://your-domain.com/' was loaded over HTTPS, but attempted to connect to the insecure WebSocket endpoint 'ws://your-domain:443/mqtt'. This request has been blocked; this endpoint must be available over WSS.
v._doConnect @ main.640d40dd027f9102c521.js:2
```
After examining the code base, I found that the MQTT library supports WSS connection. We need to pass `useSSL` option as `true`.
https://github.com/wirenboard/homeui/blob/f84679fc1a7a4475b7c284a4ac429ec34492accf/app/lib/mqttws31.js#L971
This PR adds the check if the …
> Added ability to use SSL for MQTT connections on port 443

- app/scripts/services/devicedata.js
- debian/changelog
При добавлении устройства или рестарте serial получалось, что строчки с освещением и уровнем шума считались текстовыми по умолчанию, так как в схеме соответствия типа устройства и типа отображения не было ничего задано про lux и sound_level. При обновлении страницы поля меняли тип отоборажения с text на value - менялось положение чисел.
Добоавила в схему, теперь сразу все нормально
> Add lux, sound_level device types

- app/styles/css/svg-edit-page.css
- debian/changelog
> Fit SVG to page height in dashboard editor

- app/scripts/i18n/help/en.json
- app/scripts/i18n/help/ru.json
- app/views/help.html
- debian/changelog
В кастомных сборках нам надо иметь возможность поменять информацию на help страничке без пересборки homeui. Сейчас это все находится в скомпиленом `main.*.js` и в переводах, и подменить help таким образом не просто. С этим же изменением достаточно будет заменить `help.content` в json файле c переводами.
> Move help page content to translations

- app/scripts/json-editor/group-editor.js
- debian/changelog
Для параметров из шаблонов устройств, у которых не стоял признак, что они обязательные, не рисовался редактор.
Теперь рисуется
> Fix editor for not required parameters

- app/scripts/react-directives/network-connections/connectionsStore.js
- app/scripts/react-directives/network-connections/singleConnectionStore.js
- debian/changelog
1. Изменить can соединение
2. Сохранить => появляется connection_uuid поле
3. Перейти к другому соединению => получим "Есть несохранённые изменения"
> Fix can connection saving

- app/scripts/controllers/backupController.js
- app/scripts/controllers/diagnosticController.js
- app/views/system.html
- debian/changelog
Fix downloading diagnostic archive simultaneously with uploading fit-image
Если загружать fit в контроллер и в тот же самый момент скачать диагностический архив или rootfs, загрузка fit'а прервётся. Проблема была в том, что все загрузки делались через смену location, а это приводило к полной перезагрузке страницы
> Fix uploading fit-image

- app/styles/css/svg-view-page.css
- debian/changelog
Backport of https://github.com/wirenboard/homeui/pull/487
> Remove bottom padding in hmi mode (#487)

- app/scripts/react-directives/edit-svg-dashboard/editSvgDashboardPage.jsx
- app/scripts/react-directives/edit-svg-dashboard/visualBindingsEditor.jsx
- app/scripts/react-directives/forms/forms.jsx
- app/scripts/react-directives/forms/optionsStore.js
- debian/changelog
* Fix SVG bindings parameters editor layout on medium screens
* Remove clear button from option selects in SVG bindings parameters editor
Было
Стало
> Fix SVG bindings parameters editor

- app/styles/main.css
- debian/changelog
было
https://github.com/wirenboard/homeui/assets/25829054/63c0482b-917a-4100-88da-9d4b70e34955
стало
https://github.com/wirenboard/homeui/assets/25829054/9e2665f1-3a95-4efb-b784-d58673df70ac
> css: fix History input box overlapping

- app/scripts/controllers/diagnosticController.js
- debian/changelog
не работал diag-collect, если ходить через клауд
симптомы - крутилка крутится, и ничего не происходит
было:
https://github.com/wirenboard/homeui/assets/25829054/b8a66761-6ae9-44d8-9179-ac2a0f487f36
стало:
https://github.com/wirenboard/homeui/assets/25829054/c8df1bcd-b83f-4133-a672-69f2172311f8
без клауда - тоже чекнул; не сломалось
> fix diag-collect "download" button, if connected via cloud

- app/scripts/json-editor/disabled-editor-wrapper.js
- debian/changelog
Use wb.disabledEditorText instead of inputAttributes.placeholder as a source for disabled optional parameter overlay text
При редактировании параметров в json-editor, можно указать, что необязательный параметр рисуется с чекбоксом. Если чекбокс отмечен, активируется редактор для этого параметра. Если чекбокс не отмечен, то редактор делается неактивным. Для некоторых редакторов можно прописать текст, который будет отображаться поверх неактивного редактора. Текст брался из схемы параметра из inputAttributes.placeholder. Всё это наша доработка, а не стандартный функционал json-editor'а. Этот же текст используется для самого редактора, если ничего не задано. Оказалось, что это нудобно, и надо иметь разные тексты.
Добавил wb.disabledEditorText, в котором можно указать текст оверлея
В старой …
> Fix optional parameter overlay in json-editor

- app/scripts/directives/displaycell.js
- debian/changelog
Раньше за отображение текста отвечал div с классом text-cell, в котором есть overflow-x: auto. Это добавляло длинному тексту скролл по ширине. 
[Тут](https://github.com/wirenboard/homeui/pull/434) обернули всё в ещё один div. Этот div просто расширяется на всю длину текста. Пришлось прописывать ему явно overflow-x
А почему бы не воткнуть overflow-x в класс display-cell-content? У нас странная вёрстка ячеек с числовым значением и единицами измерения. Единицы измерения ограничены шириной в 20px и фактически часто сейчас переполняются. Если сделать overflow-x в класс, у таких ячеек тоже появится скролл.
Вот так
> Fix displaying of cells with long text

- app/scripts/json-editor/group-editor.js
- debian/changelog
If a group in parameter is not defined in groups array show the parameter in root group
> Fix json-editor groups-editor groups display

- app/scripts/directives/displaycell.js
- debian/changelog
Chrome принудительно рисует скрол, даже если текст помещается. Убрал это поведение
> Fix displaying of cells with long text in Chrome

- app/index.ejs
- debian/changelog
Пользователь заметил, что обновиться для нового релиза можно не только на testing, так что поменял тут ссылку на фиты в целом. Обновлению всё равно почти два года.
> fix link to FIT image repo in Bullseye advert

- app/scripts/react-directives/network-connections/pageStore.js
- debian/changelog
Handle uncaught (in promise) error on cancel
Если при создании соединения нажать "Отмена", в консоль выпадет отмена. Ни на что не влияет, но не красиво.
> Handle network connection creation cancel

- app/scripts/services/pagestate.js
- debian/changelog
При переходе со страницы с несохранёнными изменениями выскакивает диалог предупреждение. Он был сломан. Переход всё расно осуществлялся, не смотря на то, что нажали в диалоге. Это я сломал, когда перешёл на angular-ui-router 1.x, в нё м изменились события при переходе между состояниями.
> Fix dirty page confirm dialog

- app/scripts/json-editor/wb-bootstrap3-theme.js
- debian/changelog
Текст при переносе уезжал. Зачем там этот отступ был, не понимаю
> Remove tab text left margin in json-editor

- app/scripts/json-editor/first-oneof-editor.js
- app/scripts/json-editor/wb-json-editor.js
- app/styles/css/device-manager.css
- debian/changelog
The editor shows only first oneOf item
Для редактирования и валидации конфига wb-mqtt-serial теперь используется одна и та же схема. Проблема в том, что параметр `slave_id` может быть задан в конфиге числом или строкой. Это описано в схеме как oneOf. json-editor в таком случае рисует выпадающий список с выбором типа редактора. Это всё выглядит некрасиво. Сделал редактор, который отображает только первый элемент из oneOf и не даёт переключаться. wb-mqtt-serial при этом отдаёт в web-интерфейс `slave_id` всегда как строку.
> Add customized oneOf editor to json-editor

- app/scripts/react-directives/components/json-editor/jsonEditor.jsx
- app/scripts/react-directives/device-manager/deviceTabStore.js
- debian/changelog
json-editor modifies resulting JSON after initialization. It adds properties with default values. It is not tracked as config modification now
Здесь первое изменение от json-editor просто сохраняется как текущее значение, т.к. фактически это просто добавление полей со значениями по умолчанию. При сохранении в конфиг они вычищаются, а тут добавляются снова.
Это хорошо проявлялось после сохранения настроек и при переключении между вкладками устройств. К сожалению, остался ещё баг в json-editor, из-за которого при переключении между устройствами всё ещё может измениться json, хотя фактически настройки не изменятся
> Fix unsaved changes tracking

- app/scripts/react-directives/device-manager/configUtils.js
- app/scripts/react-directives/device-manager/pageStore.js
- debian/changelog
- Не падаем, если в конфиге нет параметра `ports` 
- Выводим текcт ошибки, если это ошибка RPC
> Improve wb-mqtt-serial config loading errors handling

- app/scripts/json-editor/group-editor.js
- debian/changelog
Кэшировалась только одна функция. 
У нас есть параметры, которые имеют разную структуру в зависимости от условия. Такие параметры имеют схему с oneOf, где у каждого элемента списка oneOf своё условие. В коде checkCondition вызывается с разными схемами, но тут уже есть прокэшированная функция, и она используется всегда, независимо от реальной схемы. 
Сделал кэширование не одной функции, а набора функций
> Fix conditions cache for oneOf editors

- app/scripts/services/mqttService.js
- debian/changelog
Do not disconnect from controller after receiving malformed data from MQTT
Мы предполагаем, что в топике будет корректная UTF8 строка. Если там не UTF8, `message.payloadString` выкидывает исключение, которое никак не обрабатывается и приводит к отключению вебсокета.
> Handle malformed MQTT data

- app/styles/css/device-manager.css
- app/styles/css/scan.css
- debian/changelog
В хромиуме рисовались неактивные скроллбары
> Remove useless scrollbars on wb-mqtt-serial config page

- app/scripts/react-directives/device-manager/config-editor/portTab.jsx
- app/scripts/react-directives/device-manager/config-editor/tabsStore.js
- app/styles/css/device-manager.css
- debian/changelog
После удаления устройства, фокус всегда переходил на самый первый порт, сделал, чтоб переходил на ближайшее устройство или порт
> Move selection to next device after deletion

- app/scripts/controllers/historyController.js
- debian/changelog
Сохраняю размер полотна с графиком. Раньше, чем больше графиков было, тем оно было сплюснутее, т.к. место под легенду расходовалось
> Preserve history plot height

- app/scripts/react-directives/device-manager/scan/scanPageStore.js
- debian/changelog
Если в шаблоне устройства была прописана версия прошивки, то проверка валилась, т.к. для сравнения передавалась не строка с версией, а объект
> Fix firmware version checking

- app/scripts/json-editor/wb-json-editor.js
- debian/changelog
`angular.merge` падал, если не было параметра `item.options`.
Коллеги сделали новый шаблон для WB-MRWM2, на котором это вылезло
> Fix json-editor error handling

- app/styles/css/new.css
- debian/changelog
Текст переносится на новую строку, все выравнено по центру.
> fix device units white space

- app/scripts/react-directives/network-connections/network-connections.js
- debian/changelog
Теперь отслеживаем переподключились ли мы, и ексли да то прячем алерт о дисконнекте.
> hide network disconection alert on reconnect

- app/scripts/react-directives/device-manager/common/deviceTypesStore.js
- app/scripts/react-directives/device-manager/config-editor/deviceTab.jsx
- app/scripts/react-directives/device-manager/config-editor/deviceTabStore.js
- debian/changelog
Не показываем кнопку поиска отключенных устройств, если это не устройство WirenBoard. Всё равно ничего не найдём, т.к. поиск заточен под WB
> Allow to find only Wiren Board disconnected devices

- app/scripts/controllers/historyController.js
- debian/changelog
Uptime передаётся строками и рисовался как набор строк. 
Теперь при отрисовке графика перевожу время в секунды и подрисовываю точечки в момент перезагрузки.
Ещё пришлось руками вычислять подписи для оси ординат
Было
Стало
> Fix uptime history plot

- app/scripts/react-directives/device-manager/scan/searchDisconnectedScanPageStore.js
- debian/changelog
Scan status with error prevented from filtering devices by type
Искали WB-LED, а показываем всё подряд, а должны показывать только того типа, что ищем
Ошибка в статусе - нормальное состояние, там могут быть ошибки сканирования по другим портам. Это не причина показывать всё, что насканировали
> Fix filter when searching for disconnected devices

- app/scripts/react-directives/device-manager/config-editor/configuredDevices.js
- app/scripts/react-directives/device-manager/config-editor/portTabStore.js
- debian/changelog
WB devices can operate regardless to stop bits setting, so do not use it in configured devices matching
> Fix configured devices matching

- app/scripts/react-directives/device-manager/config-editor/configEditorPageStore.js
- app/scripts/react-directives/device-manager/config-editor/tabsStore.js
- debian/changelog
При запросе версии прошивки у вновь подключившегося устройства использовались настройки выбранного в интерфейсе порта. Выбран мог быть совсем не тот порт, на котором подключилось устройство
> Fix requesting firmware info of reconnected devices

- app/scripts/react-directives/device-manager/scan/scanPageStore.js
- debian/changelog
Correctly specify port in RPC request
Неверно передавался порт в запросе
> Fix searching of a disconnected device

- app/styles/main.css
- debian/changelog
Теперь все пробелы отображаются, а не схлопываются
> Do not collapse white spaces in rules console

- app/scripts/react-directives/device-manager/config-editor/configEditorPageStore.js
- debian/changelog
* Fix SN when setup MAP devices
* Use standard modbus for device's port configuration
https://wirenboard.youtrack.cloud/issue/SOFT-4563
1. Настройка адреса устройства выполняется через команду быстрого модбаса с использованием серийного номера. Серийный номер для счётчиков MAP вычисляется из значений регистров 270, 271, для остальных устройств берётся значение этих регистров без изменений. Для выполнения команды быстрого модбаса надо передавать не серийник, а число из регистров. Проверяю, что это MAP и модифицирую параметр для запроса.
2. Настройки порта делаю командами обычного модбаса без посылки серийника
3. Ральше серийник из строки превращался в целое число. Но есть серийники со старшим битом в 1, в результате в JSON попадало отрицательное число, запрос не выполнялся. Изменил …
> Fix SN when setup MAP devices

- .gitignore
- app/scripts/components/json-editor/angular-json-editor.js
- app/scripts/json-editor/select-with-hidden-items.js
- app/scripts/react-directives/mbgate/selectControlsModal.jsx
- debian/changelog
- package-lock.json
* The bugs was a result of building with fresh libraries from npm. Add package-lock.json to fix dependencies
* Remove double validation on JSONEditor creation. 'ready' and 'change' events are triggered in the same place
* Fix iteration over select options
* Fix channels selection in mbgate editor
backport of https://github.com/wirenboard/homeui/pull/645
> Bugfix/json editor bug (#645)

- app/scripts/react-directives/forms/oneOfStore.js
- debian/changelog
setValue does not set value to selected sub store. It only changes select's value. Now sub store is populated properly
backport of https://github.com/wirenboard/homeui/pull/658
> Fix OneOfStore (#658)

- app/index.ejs
- app/styles/main.css
Не показываю предупреждения о ненастроенных https и пользователях в полноэкранных режимах. Эти режимы предназначены для организации всяких панелек, так админ и https не сильно нужны, а пугать будут
> Hide alert in hmi and fullscreen modes

- debian/changelog
- frontend/app/scripts/json-editor/json-editor-ru.js
- frontend/app/scripts/json-editor/wb-json-editor.js
Изменен текст ошибки oneOf
Было
- Один или несколько параметров заданы неверно
- One or more parameters are invalid
Стало
- Параметры заданы неверно
- Parameters are set incorrectly
> Change text for oneOf JSON-editor error

- debian/changelog
- frontend/app/scripts/json-editor/group-editor.js
Multiple editor sets null as default value in disabled state, so set the correct default value
https://github.com/user-attachments/assets/e8f1b35e-edc9-4bf9-8078-ae01c0088119
Значения по умолчанию не подставлялись в редактор. Это баг json-editor, он некорректно вычисляет значение по умолчнию. Лезть в json-editor не хочу, поправил в коде homeui, который использует этот редактор
https://github.com/user-attachments/assets/3397eaa3-da97-482b-86fa-a34280af6228
Открыть шаблон MAI6 и выбрать для канала 4-20
> Fix default value for parameters in group-editor

- Jenkinsfile
- debian/changelog
- debian/control
- debian/wb-mqtt-homeui.lintian-overrides
- frontend/Makefile
* Install rimraf before make clean
```sh
dh clean --parallel --with config-package
dh_auto_clean
make -j8 clean
make[1]: Entering directory '/home/jenkins/builder/workspace/wirenboard_homeui_feature_trixie/project'
make -C frontend clean
make[2]: Entering directory '/home/jenkins/builder/workspace/wirenboard_homeui_feature_trixie/project/frontend'
npm run clean
> homeui@0.1.0 clean
> node_modules/.bin/rimraf -G dist coverage ./tmp
sh: 1: rimraf: not found
```
Не стреляло, так как в devenv был предустановлен rimraf.
* Enable lintian
Nothing
> Fix build, enable lintian

- debian/changelog
- frontend/app/scripts/react-directives/device-manager/config-editor/deviceTabStore.js
Show notification about new bootloader only if a new firmware is also available
Показываем оповещение о новом загрузчике только, если есть и новая прошивка. Аналогично ведёт себя консольная утилита.
Загрузчики выходят слишком часто, это раздражает пользователей, а толку мало.
Другой задачей будут решать, как оповещать только о нужных обновлениях. 
> Do not show new bootloader notification

- debian/changelog
- frontend/app/scripts/react-directives/device-manager/config-editor/configuredDevices.js
- frontend/app/scripts/react-directives/device-manager/scan/scanPageStore.js
Убрал логику поиска настроенных среди отсканированных устройств. Она не всегда работала https://wirenboard.youtrack.cloud/issue/SOFT-5148/MR6C-NC-vsegda-otobrazhayutsya-v-skanirovanii-kak-novye
Теперь информацию о настроенных устройствах выдает сам сканер
Баг исправили
Настроил как в тикете и сканировал
```
echo "deb http://deb.wirenboard.com/all experimental.new-scan main" > /etc/apt/sources.list.d/new-scan.list
```
> Use configured_device_type from wb-device-manager scn RPC

- debian/changelog
- frontend/app/scripts/react-directives/mbgate/pageStore.js
Поменял для `mbgate` размер `varchar` регистра по умолчанию на 1.
https://github.com/wirenboard/wb-mqtt-mbgate/pull/59
> change mbgate default varchar register size to 1

- debian/changelog
- frontend/src/stores/device/device.ts
- frontend/webpack.config.js
Исправил ошибку в процессе загрузки страницы интеграции с Алисой.
Проблема была в обращении к localStorage к объекту с ключём foldedDevices. Если его нет, для null пытались вызвать includes и получали исключение. Это исключение никак не обрабатывалось. Оно выпадало в контексте обработки сообщения от MQTT. Соединение с брокером рвалось.
Настройками можно пользоваться
Удалил из localStorage foldedDevices и грузил страницу Алисы
> Fix loading of Alice integration page

- debian/changelog
- frontend/app/scripts/utils/httpsUtils.js
При открытии интерфейса через браузер, установленный на контроллере, не делаем принудительный переход на https и не ругаемся, если он не настроен
Часто используется для hdmi-экранов, там https не важен
Локально
https://wirenboard.youtrack.cloud/issue/SOFT-5893/Ne-proveryat-HTTPS-dlya-lokalnyh-podklyuchenij
> Do not redirect to HTTPS on localhost

- backend/configs/usr/share/wb-mqtt-homeui/nginx/default.conf
- backend/wb/homeui_backend/main.py
- debian/changelog
Использую одну и ту же cookie для HTTP и HTTPS
Если пользователь получил куки через HTTPS, а потом переключился на HTTP, он не мог залогиниться. Бэк выдавал новую куки с тем же именем, но без Secure. Браузеры не принимают такие куки, т.к. они перезаписывают уже сохранённые куки с Secure. Ошибок внятных не выдаётся, просто не логинится.
Попробовал то, что описано в тикете https://wirenboard.youtrack.cloud/issue/SOFT-6036/Avtorizaciya-v-https-meshaet-http
> Use the same cookie for HTTP and HTTPS
