wirenboard/homeui

app/index.html

Что ж вы себя не любите? Картинки поставили, но не сделали их ссылками. Не порядок 😀

ссылки на contactless и carbonfay.ru

---

app/scripts/directives/cell.js
app/scripts/directives/switchcell.html
app/scripts/directives/switchcell.js
app/scripts/directives/widget.html
app/scripts/directives/widget.js
app/scripts/services/devicedata.js
app/styles/main.css

Revert "Инвертирование переключателей #31"

---

app/scripts/directives/cell.js
app/scripts/directives/switchcell.html
app/scripts/directives/switchcell.js
app/scripts/directives/widget.html
app/scripts/directives/widget.js
app/scripts/services/devicedata.js
app/styles/main.css
app/views/devices.html
app/views/widgets.html

Версия с поправленным багом с ошибкой отображения виджетов.

#31 инвертирование переключателей

---

app/scripts/app.js
app/scripts/services/mqttService.js
app/scripts/services/rpc.js

Порядок загрузки данных по MQTT #28

---

app/index.ejs
app/styles/css/new.css

WB#51 fix menu width

---

app/scripts/directives/displaycell.html
app/scripts/directives/displaycell.js
app/styles/main.css
app/views/devices.html

resolve issue [#45 ](https://github.com/contactless/homeui/issues/45)

WB#45 add history btn

---

app/index.ejs
app/styles/main.css

resolve issue [#52](https://github.com/contactless/homeui/issues/52)
Исправил стили для мобильного меню, чтобы пункты отображались во всю ширину:
Добавил скрытие мобильного меню при выборе пункта или конечного, если пункт такие содержит

WB#52-collapse_mobile_menu_on_select

---

app/styles/main.css

resolve issue [#58](https://github.com/contactless/homeui/issues/53)
Исправил css стиль для фона так, чтобы белым был весь экран

WB#53-white_background_height

---

app/scripts/directives/buttoncell.html
app/scripts/directives/buttoncell.js
app/scripts/directives/widget.html
app/scripts/directives/widget.js
app/styles/main.css

resolve issue [#44](https://github.com/contactless/homeui/issues/44)

WB#44-renaming_pushbutton

---

app/scripts/app.js
app/scripts/services/roles.factory.js

resolve issue #79 
При инициализации приложения явно заношу дефолтные настройки подключения (host: localhost, port: 18883) в localeStorage.
При инициализации ролей явно заношу дефолтную роль (1)  в localeStorage.

WB#79_first-open-behavior-fix

---

app/scripts/controllers/webUiController.js

resolve issue #80 
Добавил объект с методом `setDefaultDashboard` в область видимости

WB#80_default-dashboard-selection-fix

---

app/scripts/app.routes.js
app/scripts/controllers/devicesController.js
app/styles/css/new.css
app/styles/main.css
app/views/devices.html

resolve issue #56 
Раздел с устройствами был переделан через новые компоненты `accordion` библиотеки `angular-ui`.
Панели с устройствами теперь могут сворачиваться. Когда они свёрнуты контент в них не рендерится для экономии ресурсов.
Если устройств больше, чем `collapseDevicesAfter` все устройства кроме 1 будут отображаться свёрнутыми.
Если перейти по адресу `/devices/deviceId` будет развёрнуто конкретное устройство.

WB#56-remake_devices_screen

---

app/scripts/controllers/scriptsController.js
app/views/scripts.html

resolve [issue 86](https://github.com/contactless/homeui/issues/86)
Удалил из разметки и контроллера методы и элементы работы с скриптами, которые больше не поддерживаются на backend'e

WB#86-remove-unsupported-controls-on-scripts-page

---

app/scripts/controllers/accessLevelController.js
app/views/access-level.html

resolve [issue 87](https://github.com/contactless/homeui/issues/87)<br>
Изменил условие появления alert'a `"I take full responsibility"` и поведение кнопки `apply` при смене роли

WB#87-full-responsibility-alert-fix

---

app/index.ejs
app/scripts/app.routes.js
app/scripts/controllers/scriptController.js
app/views/scripts.html

resolve issue #85 
Поверхностно переименовал раздел ```Scripts -> Rules```

WB#85-renaming-scripts-section

---

app/scripts/controllers/widgetsController.js
app/views/widgets.html

resolve issue #93 
Исправил получение типа канала во view файле

WB#93_fix-display-of-types-in-widgets

---

app/index.ejs
app/scripts/app.js
app/scripts/controllers/navigationController.js
app/styles/css/new.css
app/styles/main.css

resolve issue #96
Переделал дефолтное мобильное bootstrap меню по подобию меню из приложения gmail

WB#96_new-mobile-menu

---

app/scripts/controllers/historyController.js

resolve issue #97 
Прочитал документацию по Plotly.js, нашёл в ней флаг для исправления описанной в issue проблемы.

WB#97_graph-y-values-fix

---

app/scripts/controllers/historyController.js
app/views/history.html

Добавил кнопку, создающей из таблицы истории устройства .csv файл

WB#116 history downloading

---

app/scripts/directives/displaycell.html
app/scripts/directives/displaycell.js
app/scripts/directives/explicitchanges.js
app/scripts/directives/textcell.html
app/scripts/directives/valuecell.html

Disabled send form when press Enter on editable textfield in widget
Disabled copy paste when field is editable
Add commit value by change event

Fix change field with type value and param meta/writable = 1

---

app/index.ejs
app/scripts/app.js
app/styles/main.css

https://github.com/contactless/homeui/issues/148

Add loader when app loading and starting

---

app/scripts/controllers/historyController.js
debian/changelog

History load fix #126

---

convert_config_v1v2.py
debian/changelog

Merge only /config/widgets/#, /config/rooms/#, /config/default_dashboard/#, /config/dasboards/#

Error in config conversion from v1.x is fixed.

---

app/scripts/controllers/historyController.js
app/styles/main.css
debian/changelog

* Always show chart toolbar
* Chart toolbar icons are made bigger
* New chart hover tooltip layout

History chart improvements

---

app/scripts/directives/widget.html
app/scripts/directives/widget.js
debian/changelog

Rebase of https://github.com/wirenboard/homeui/pull/204

Don't allow to change widget's id

---

.gitmodules
Jenkinsfile
debian/control

Корректно соберётся с devenv из https://github.com/wirenboard/wirenboard/pull/76

add Jenkinsfile

---

app/scripts/controllers/historyController.js
app/views/history.html
debian/changelog

Rebase of https://github.com/wirenboard/homeui/pull/214

Min and max values in charts as bands not as lines

---

app/scripts/controllers/historyController.js
debian/changelog

Rebase of https://github.com/wirenboard/homeui/pull/219

Multiple axes are added to charts on History page

---

app/index.ejs
app/scripts/app.js
app/scripts/app.routes.js
app/scripts/controllers/dateTimePickerModalController.js
app/scripts/controllers/logsController.js
app/scripts/directives/resize.js
app/scripts/services/logsProxy.js
app/styles/main.css
app/views/dateTimePickerModal.html
app/views/logs.html
debian/changelog
debian/control
package.json
webpack.config.js

Rebase of https://github.com/wirenboard/homeui/pull/217

Logs page implementation

---

app/views/dashboard-svg.html
debian/changelog

Rebase of https://github.com/wirenboard/homeui/pull/229

SVG dashboard edit button translation fix

---

app/scripts/controllers/historyController.js
debian/changelog

Rebase of https://github.com/wirenboard/homeui/pull/230

Dates calculation for history table is fixed

---

app/scripts/controllers/historyController.js
debian/changelog

Rebase of https://github.com/wirenboard/homeui/pull/236

Loading of history unavailable channels is fixed

---

app/3rdparty/angular-json-editor.js
debian/changelog

Rebase of https://github.com/wirenboard/homeui/pull/233

Russian translation for json-editor built-in messages

---

app/scripts/controllers/configsController.js
app/views/configs.html
debian/changelog
debian/control

Rebase of https://github.com/wirenboard/homeui/pull/234

Config titles and descriptions translation support

---

app/3rdparty/angular-json-editor.js
debian/changelog

Rebase of https://github.com/wirenboard/homeui/pull/255

New editor for poll_interval in wb-mqtt-serial.conf

---

app/scripts/services/rpc.js
debian/changelog

Rebase of https://github.com/wirenboard/homeui/pull/258

RPC methods availability check is added

---

.gitignore
app/index.ejs
app/scripts/app.js
app/scripts/app.routes.js
app/scripts/controllers/serialMetricsController.js
app/scripts/i18n/app/en.json
app/scripts/i18n/app/ru.json
app/scripts/i18n/serial-metrics/en.json
app/scripts/i18n/serial-metrics/ru.json
app/scripts/services/serialMetricsProxy.js
app/views/serial-metrics.html
debian/changelog

Rebase of https://github.com/wirenboard/homeui/pull/251

wb-mqtt-serial metrics page

---

app/views/system.html
debian/changelog

fix hide button lable anfter firmware update is complete

---

app/3rdparty/angular-json-editor.js
debian/changelog

Починил удаление и перемещение элементов в массивах, которые вкладками отображаются.

Deletion of array items in config editors is fixed

---

debian/changelog
webpack.config.js

So it will be reloaded from server if content changes
Rebase of https://github.com/wirenboard/homeui/pull/285

 A hash is added to main.css file name

---

app/scripts/controllers/historyController.js
debian/changelog

Добавил округление до целого для min_interval

Changed min_interval from float to integer

---

app/scripts/components/json-editor/angular-json-editor.js
app/scripts/components/json-editor/collapsible-multiple-editor.js
app/scripts/components/json-editor/json-editor-ru.js
app/scripts/components/json-editor/unknown-device-editor.js
debian/changelog

* "unknown-device" editor for editing configs of devices with invalid templates
* wb.hide_from_selection option is added for "wb-multiple" editor. It hides element from selection list
В списке устройств выглядит так

Special editor for unknown devices

---

app/scripts/components/json-editor/angular-json-editor.js
app/scripts/components/json-editor/select-with-hidden-items.js
debian/changelog

Hidden items can be specified in options.enum_hidden of enum's json schema

Enum editor with hidden items

---

app/scripts/components/json-editor/select-with-hidden-items.js
debian/changelog

Для работы скрытия модулей в hwconf (как ты подсказал)
Попутно потыкал настройки serial - вроде ничего не поломалось

enum-editor-with-hidden-items supports dynamic lists-building

---

app/scripts/components/json-editor/angular-json-editor.js
app/scripts/components/json-editor/collapsible-multiple-editor.js
app/scripts/components/json-editor/group-editor.js
app/scripts/components/json-editor/json-editor-ru.js
debian/changelog

Rebase of https://github.com/wirenboard/homeui/pull/310

Groups editor

---

app/scripts/components/json-editor/group-editor.js
debian/changelog

* ui_options.wb.disable_title support for groups is added
* Params ordering fix

Nested groups titles display is fixed in config editor

---

app/scripts/components/json-editor/group-editor.js
debian/changelog

Rebase of https://github.com/wirenboard/homeui/pull/316

Support for device parameters specified as array

---

app/scripts/components/json-editor/angular-json-editor.js
debian/changelog

It can be used only if default value is set for array

Do not use lazy-tabs editor for all tabs (#321)

---

app/scripts/components/json-editor/group-editor.js
debian/changelog

Support for descriptions in config groups is added

---

app/scripts/components/json-editor/angular-json-editor.js
app/scripts/components/json-editor/json-editor-ru.js
app/scripts/components/json-editor/wb-bootstrap3-theme.js
debian/changelog

Messages about invalid port or device parameters are made more understandable

---

app/scripts/components/json-editor/collapsible-array-editor.js
app/styles/main.css
debian/changelog

Support for copying device configs is added

---

app/scripts/components/json-editor/angular-json-editor.js
app/scripts/components/json-editor/collapsible-array-editor.js
debian/changelog

https://wirenboard.bitrix24.ru/company/personal/user/12/tasks/task/view/36500/
Тогда сделал прокрутку до добавленного устройства, но, говорят, что неудобно крутить обратно к кнопке.

Add new items on top of an array in collapsible-list editor

---

Makefile
app/index.ejs
app/scripts/i18n/app/en.json
app/scripts/i18n/app/ru.json
debian/changelog
debian/control

Add advert for upgrade via FIT

---

app/scripts/components/json-editor/collapsible-multiple-editor.js
app/scripts/components/json-editor/wb-array-editor.js
app/scripts/components/json-editor/wb-bootstrap3-iconlib.js
app/scripts/components/json-editor/wb-bootstrap3-theme.js
debian/changelog

This is used in network connections editor to show legacy items that should be removed.

json-editor: array tabs highlighting support + alerts in editor

---

app/scripts/app.js
app/scripts/controllers/webUiController.js
debian/changelog

Test case:
```js
window.navigator.languages = ["ru-RU", "ru", "en-US", "en"]
```

Fix default language detection

---

app/scripts/i18n/react/locales/en/translations.json
app/scripts/i18n/react/locales/ru/translations.json
app/scripts/react-directives/network-connections/connectionStore.js
app/scripts/react-directives/network-connections/networkConnections.jsx
app/scripts/react-directives/network-connections/tabs.jsx
app/styles/main.css

Add autoconnect notice

---

app/scripts/app.js
app/scripts/controllers/scriptsController.js
debian/changelog

MQTT client ID:
* Before: `contactless-EU6pnwim6x`
* After: `wb-mqtt-homeui-EU6pnwim6x`

Form identifiable client ID for MQTT connection

---

Jenkinsfile
Makefile
app/scripts/components/json-editor/group-editor.js
debian/changelog
debian/control

backport of https://github.com/wirenboard/homeui/pull/371 into bullseye-upgrade release + version bump

fix displaying of conditional config parameters

---

app/scripts/react-directives/network-connections/jsonEditor.jsx
debian/changelog

У меня воспроизводится так:
1. Удаляем все wi-fi клиенты
2. Поднимаем АР
3. Заходим через AP
4. В интерфейсе настроек протыкиваем все соединения. Остаёмся на AP
5. Нажимаем "добавить", выбираем клиента
Получем скрин

Recreate json-editor if schema changes

---

app/scripts/directives/rangecell.js
app/scripts/services/devicedata.js
debian/changelog

чинили большие значения в range-контролах, а в стейбл - забыли перетащить
пользователи в чатике увидели

Feature/60274 range cell (#424)

---

app/scripts/react-directives/common.jsx
app/scripts/react-directives/components/modals/confirmModal.jsx
app/scripts/react-directives/components/modals/confirmModalState.js
app/scripts/react-directives/components/modals/modals.jsx
app/scripts/react-directives/firmware-update/firmwareUpdateWidget.jsx
app/scripts/react-directives/forms/booleanStore.js
app/scripts/react-directives/forms/formStore.js
app/scripts/react-directives/forms/forms.jsx
app/scripts/react-directives/forms/numberStore.js
app/scripts/react-directives/forms/stringStore.js
app/scripts/react-directives/forms/stringValidators.js
app/scripts/react-directives/network-connections/modals.jsx
app/scripts/react-directives/network-connections/network-connections.js
app/scripts/react-directives/network-connections/networkConnectionsPage.jsx
app/scripts/react-directives/network-connections/pageStore.js
app/scripts/react-directives/network-connections/switcherEditor.jsx
app/scripts/react-directives/network-connections/switcherStore.js
app/scripts/react-directives/view-svg-dashboard/viewSvgDashboardPage.jsx
debian/changelog

Вынес в один каталог файлики, связанные с формами (модели и компоненты), чтобы было удобнее переиспользовать

Move form related files into separate folder

---

app/scripts/json-editor/group-editor.js
debian/changelog

Пользователи 2304 на форуме заметили эту проблему. Нужен бекпорт

Fix loading wb-mqtt-serial config (#436)

---

app/scripts/app.js
debian/changelog

Серый фон не исчезал. Это сломалось при переезде на новый ui-router
https://github.com/wirenboard/homeui/assets/86825564/3312df21-8c28-4153-a791-38f3ab3a8789

Fix menu overlay hiding

---

app/scripts/directives/valuecell.js
debian/changelog
debian/control

Fix fractional value parsing

---

app/scripts/react-directives/network-connections/pageStore.js
debian/changelog

При нажатии на отмену в диалоге подтверждения удаления соединения, соединение всё равно удалялось

Fix network connection deletion cancel

---

app/scripts/app.js
app/scripts/i18n/react/locales/en/translations.json
app/scripts/i18n/react/locales/ru/translations.json
app/scripts/react-directives/cloud-status/cloud-status.js
app/scripts/react-directives/cloud-status/cloudStatusWidget.jsx
app/scripts/react-directives/cloud-status/store.js
app/views/system.html
debian/changelog

Плюсом добавил проверку на https (если используется tls, то к mqtt подключаемся через прокси на 443)

Minimal Cloud support

---

Jenkinsfile
Makefile
app/scripts/app.js
app/scripts/controllers/cloudWidgetController.js
app/scripts/i18n/system/en.json
app/scripts/i18n/system/ru.json
app/views/system.html
debian/changelog
debian/control
package.json

* add wb cloud widget (wb-2207 release compatible)
* fix homeui package build for stretch
port of #497

Add WB Cloud widget for wb-2207 release

---

app/scripts/react-directives/cloud-status/cloud-status.js
app/scripts/react-directives/cloud-status/cloudStatusWidget.jsx
app/scripts/react-directives/cloud-status/store.js
debian/changelog

Ссылка на wb-cloud теперь указывает на сасо устройство

Cloud link points to the device

---

app/scripts/app.js
app/scripts/controllers/diagnosticController.js
app/scripts/services/mqttService.js
debian/changelog

Совсем забыл перенести сюда настройки для работы через tls

fix SSL connection support

---

app/scripts/app.js
app/scripts/controllers/diagnosticController.js
app/scripts/services/mqttService.js
debian/changelog

* fix SSL connection support
* fix diag-collect download button (like in #496)

fix SSL connection support (#502)

---

app/scripts/app.js
app/scripts/controllers/diagnosticController.js
app/scripts/i18n/react/locales/en/translations.json
app/scripts/i18n/react/locales/ru/translations.json
app/scripts/react-directives/cloud-status/cloud-status.js
app/scripts/react-directives/cloud-status/cloudStatusWidget.jsx
app/scripts/react-directives/cloud-status/store.js
app/views/system.html
debian/changelog

Компиляция #492, #496 и #501 для стабильного релиза

WB Cloud support for wb-2310

---

devserver_stretch.sh

Пока отлаживал homeui для 2207, пришлось потратить полчаса на то, чтобы вспомнить, как запустить локальный сервер для отладки. Решил собрать скрипт здесь, чтобы никому больше не пришлось страдать из-за этого.

add script to run devserver in stretch in docker

---

app/scripts/services/devicedata.js
debian/changelog

не обрабатывался error если отправлять как json

Fix error field in meta json

---

app/scripts/i18n/mqtt/en.json
app/scripts/i18n/mqtt/ru.json
app/views/MQTTChannels.html

Не очень удобно в этом разделе что-то искать без поиска.

Добавил на страницу «Каналы MQTT» простой поиск по устройствам

---

app/scripts/directives/textcell.html
app/scripts/directives/valuecell.html
app/scripts/services/devicedata.js
debian/changelog

Implements https://github.com/wirenboard/conventions/pull/7
`echo "deb http://deb.wirenboard.com/all experimental.enum main" > /etc/apt/sources.list.d/enum.list`

Add support for enums in templates

---

app/scripts/app.routes.js
app/scripts/react-directives/device-manager/device-manager.js
app/scripts/react-directives/device-manager/pageStore.js
app/scripts/react-directives/device-manager/tabsStore.js
app/scripts/services/pagestate.js
app/styles/css/device-manager.css
debian/changelog

Use Back button to navigate from device settings to the list of devices and ports in device manager in mobile mode

Use Back button in device-manager

---

app/scripts/react-directives/device-manager/deviceTab.jsx
app/scripts/react-directives/device-manager/deviceTabStore.js
debian/changelog

При переключении типа устройства через выпадающий список иногда не обновлялось содержимое редактора настроек

Fix device type selection in wb-mqtt-serial config editor

---

app/scripts/react-directives/view-svg-dashboard/svgView.jsx
debian/changelog

При ошибке в правиле, выкидывалось исключение и ломалось отображение дашборда

Fix SVG dashboard display with poorly written rules

---

configs/config.wb6.json.jinja
configs/config.wb7.json.jinja
configs/config.wb74.json.jinja
configs/config.wb8.json.jinja
debian/changelog

В SVG потенциально может встретиться например такое:
`inkscape:export-filename="C:\Users\wofs2\YandexDisk-axv-soft\Иллюстрации\Wiki\Чемодан\растровый.png"`

Fix config generation

---

app/scripts/i18n/react/locales/en/translations.json
app/scripts/i18n/react/locales/ru/translations.json
app/scripts/react-directives/device-manager/common/deviceTypesStore.js
app/scripts/react-directives/device-manager/scan/common.jsx
app/scripts/react-directives/device-manager/scan/desktop.jsx
app/scripts/react-directives/device-manager/scan/mobile.jsx
app/scripts/react-directives/device-manager/scan/scanPageStore.js
app/styles/css/scan.css
debian/changelog

Add warning if multiple device templates match the same scanned device in wb-mqtt-serial config

Add multiple matched templates warning

---

configs/config.wb6.json.jinja
configs/config.wb7.json.jinja
configs/config.wb74.json.jinja
configs/config.wb8.json.jinja
debian/changelog

Не используется, а пейлоад в mqtt увеличивает в 2 раза (~+320k)

Remove svg.original from configs

---

app/scripts/json-editor/group-editor.js
app/scripts/json-editor/wb-json-editor.js
debian/changelog

Fix validation depending from condition (#551)

---

app/scripts/controllers/historyController.js
app/scripts/controllers/widgetsController.js
app/scripts/react-directives/forms/forms.jsx
debian/changelog

* Fix History page infinite loading because of widgets without id
* Fix Widgets page display when there are widgets without id
https://wirenboard.youtrack.cloud/issue/SOFT-3659/Polzovatelskie-razdeliteli-v-vidzhetah-lomayut-interfejs

Handle widgets without id

---

app/scripts/controllers/historyController.js
app/scripts/controllers/widgetsController.js
app/scripts/react-directives/forms/forms.jsx
debian/changelog

* Fix History page infinite loading because of widgets without id
* Fix Widgets page display when there are widgets without id
Backport of https://github.com/wirenboard/homeui/pull/556

Handle widgets without id (#556)

---

app/scripts/react-directives/device-manager/config-editor/deviceTab.jsx
debian/changelog

Add delete button for unknown devices

---

app/scripts/react-directives/firmware-update/firmwareUpdateWidget.jsx

подтягивается через wb-cloud в прокси, можно проверить в staging

fw-update: use window.wbCloudProxyInfo to check if we came from a cloud

---

app/scripts/directives/textcell.html
app/scripts/directives/valuecell.html
app/scripts/directives/widget.js
app/scripts/services/devicedata.js
app/styles/main.css
debian/changelog

Теперь редактируемые поля с enum можно менять через выпадающий список

Add select for channels with enum

---

app/scripts/directives/textcell.html
app/scripts/directives/valuecell.html
debian/changelog

Тултип ломал выпадающий список

Fix tooltip

---

app/scripts/directives/textcell.html
debian/changelog

Сломал отображение текстовых полей

Fix textcell

---

app/robots.txt
debian/changelog

Запрет для индексирования поисковыми роботами

disallow indexing

---

app/index.ejs
app/scripts/app.js
app/scripts/i18n/react/locales/en/translations.json
app/scripts/i18n/react/locales/ru/translations.json
app/scripts/react-directives/exp-check/exp-check.js
app/scripts/react-directives/exp-check/expCheckWidget.js
app/scripts/react-directives/exp-check/store.js
app/scripts/react-directives/locale.js
debian/changelog
debian/control

Бэкпорт https://github.com/wirenboard/homeui/pull/576
В ченджлоге пишарм зачем-то решил поделить на ноль пробелы в конце строки.

Backport wb-2404 add probe check

---

app/scripts/react-directives/script-editor/scriptEditorPage.jsx
debian/changelog

https://wirenboard.youtrack.cloud/issue/SOFT-3852

clear rule editor history on init

---

app/scripts/react-directives/device-manager/config-editor/configuredDevices.js
app/scripts/services/mqttService.js
debian/changelog

Адреса могут быть строками, из-за этого ломается проверка уникальности адреса. Сделал перевод в числа

Fix address assignment in wb-mqtt-serial config

---

app/scripts/react-directives/exp-check/exp-check.js
app/scripts/react-directives/exp-check/expCheckWidget.js
app/scripts/react-directives/exp-check/store.js
debian/changelog

Backport of https://github.com/wirenboard/homeui/pull/591

Hide vulnerability warning (#591)

---

app/scripts/react-directives/device-manager/config-editor/configEditorPageStore.js
app/scripts/react-directives/device-manager/config-editor/configuredDevices.js
app/scripts/react-directives/device-manager/config-editor/portTabStore.js
debian/changelog

Fix adding devices connected via Modbus over TCP gateways to wb-mqtt-serial configuration

Fix adding devices to wb-mqtt-serial configuration

---

app/scripts/react-directives/device-manager/deviceTypesStore.js
app/scripts/utils/fwUtils.js
debian/changelog
test/react/serial-config/fwUtils.test.js

Не выбирался шаблон, в котором указана версия, совпадающая с текущей версией прошивки, т.к. ожидали только более новую версию

Fix fw version comparison

---

app/styles/css/new.css
debian/changelog

Исправил заезд дробной части на основную

fix decimal float

---

.gitignore
README.md
debian/changelog
package.json
webpack.config.js

Удалил неиспользуемые библиотеки из зависимостей, скрипты из package.json

remove unnecessary libs

---

app/views/logs.html
debian/changelog

логи перестали загружаться после нажатия на кнопку, бэкпорт

fix loading logs

---

app/scripts/i18n/react/locales/en/translations.json
app/scripts/i18n/react/locales/ru/translations.json
app/scripts/react-directives/common.jsx
app/scripts/react-directives/device-manager/config-editor/configEditorPageStore.js
app/scripts/react-directives/device-manager/config-editor/deviceTab.jsx
app/scripts/react-directives/device-manager/config-editor/deviceTabStore.js
app/styles/css/device-manager.css
debian/changelog

* Add link to Wiren Board Modbus device firmware recovery instruction
* Add notification about power off during Modbus device firmware update
* Fix Modbus device firmware update progress display

Add notification about firmware update

---

app/scripts/react-directives/device-manager/config-editor/configEditorPageStore.js
app/scripts/react-directives/device-manager/config-editor/portTabStore.js
app/scripts/react-directives/device-manager/deviceManagerPageStore.js
app/scripts/react-directives/device-manager/scan/scanPageStore.js
app/scripts/react-directives/device-manager/scan/searchDisconnectedScanPageStore.js
app/scripts/services/fwUpdateProxy.js
debian/changelog

Теперь, если в поиске неотвечающего устройства, выбрать устройство в режиме загрузчика, это устройство будет прошито актуальной прошивкой

Add firmware recovery

---

app/scripts/app.js
app/scripts/controllers/webUiController.js
app/scripts/i18n/help/en.json
app/scripts/i18n/help/ru.json
app/scripts/i18n/react/config.js
app/scripts/react-directives/firmware-update/firmwareUpdateWidget.jsx
app/views/web-ui.html
debian/changelog

Backport https://github.com/wirenboard/homeui/pull/472

Vendor related changes

---

app/scripts/i18n/react/locales/en/translations.json
app/scripts/i18n/react/locales/ru/translations.json
app/scripts/react-directives/device-manager/config-editor/configEditorPage.jsx
app/scripts/react-directives/device-manager/config-editor/configEditorPageStore.js
app/scripts/react-directives/device-manager/config-editor/deviceTab.jsx
app/scripts/react-directives/device-manager/config-editor/deviceTabStore.js
app/scripts/react-directives/device-manager/device-manager.js
app/scripts/react-directives/device-manager/deviceManagerPageStore.js
app/styles/css/device-manager.css
debian/changelog

Добавил возможность обновить бутлоадер у наших устройств

Add bootloader update

---

app/scripts/i18n/react/locales/en/translations.json
app/scripts/i18n/react/locales/ru/translations.json
app/scripts/react-directives/device-manager/common/deviceTypesStore.js
app/scripts/react-directives/device-manager/config-editor/deviceTab.jsx
app/scripts/react-directives/device-manager/config-editor/deviceTabStore.js
app/scripts/utils/fwUtils.js
app/styles/css/device-manager.css
debian/changelog
test/react/serial-config/fwUtils.test.js

Добавил сообщение о том, что настройки будут удалены.
Переделал панельку с сообщением об одновременно доступных для обновления прошивке и загрузчике. Раньше это были две отдельные панельки со своими кнопками, теперь решили обновлять всё разом

Add deleting settings notification

---

app/scripts/react-directives/device-manager/config-editor/deviceTabStore.js
debian/changelog

Забыл реализовать удаление ошибок при удалении устройства из конфига

Fix device deletion

---

app/scripts/directives/alarmcell.html
debian/changelog

Fix alarm title translation

---

app/scripts/json-editor/autocomplete.js
debian/changelog

[Backport](https://github.com/wirenboard/homeui/pull/664)

Fix multiple datalists for same autocompletes

---

app/scripts/directives/displaycell.js
debian/changelog

[backport](https://github.com/wirenboard/homeui/pull/691)

fix url params transition

---

app/scripts/react-directives/device-manager/scan/scanPageStore.js
debian/changelog

вендор попросил сделать как то так чтобы mio отображался по их номенклатуре. через serial это сделать нельзя, тк нет шаблона

Fix mio and mio-e

---

app/scripts/react-directives/users/pageStore.js
app/scripts/react-directives/users/usersPage.jsx

* Prevent deleting last admin
* Prevent changing last admin type

Prevent deleting last admin

---

debian/changelog
frontend/app/scripts/react-directives/components/modals/formModal.jsx
frontend/app/scripts/react-directives/components/modals/modals.jsx

* add modals without cancel
* add submit on Enter in FormModal

Modals improvements

---

backend/configs/usr/share/wb-mqtt-homeui/nginx/default.conf
backend/wb/homeui_backend/cert.py
frontend/app/index.ejs
frontend/app/scripts/app.js
frontend/app/scripts/i18n/app/en.json
frontend/app/scripts/i18n/app/ru.json
frontend/app/scripts/react-directives/users/pageStore.js
frontend/app/scripts/utils/httpsUtils.js
frontend/app/styles/main.css
frontend/app/views/logs.html
frontend/app/views/system.html
frontend/webpack.config.js

При загрузке страницы проверяем состояние сертификата для HTTPS. Если он не валидный, то запрашиваем его.
В это время крутится спиннер. Если всё удачно делаем редирект на HTTPS, если нет - показываем предупреждение
Нельзя ничего сделать на странице, пока не станет ясно, что с сертификатом
1. Отключил выход в сеть на контроллере, всё поставил. Убедился, что страница загружается быстро и есть сообщение о проблеме с HTTPS
2. Включил инет на контроллере, нажал F5, убедился, что спиннер крутится пока запрашивается сертификат, а потом делаетс редирект на HTTPS
3. Выключил инет на контроллере, …

Add UI for certificate request

---

frontend/Makefile
frontend/app/scripts/utils/httpsUtils.js

Перенаправляем на https, если знаем, что сертификат корректный, но наш хитрый DNS недоступен
Если на клиенте нет доступа в интернет, всё равно используем https
Отключил инет на компе, открыл интерфейс контроллера, убедился, что меня перебросило на https

Redirect to HTTPS if certificate is valid

---

debian/changelog
frontend/app/scripts/react-directives/device-manager/config-editor/deviceTab.jsx
frontend/app/scripts/react-directives/device-manager/config-editor/settingsTabStore.js

* Fix wrong duplicate MQTT topic error
* Fix wrong error in common wb-mqtt-serial settings
1. Ругалось на повторяющиеся MQTT топики, хотя они не повторялись. Сломал в прошлом коммите
2. Ругалось на кривые общие настройки wb-mqtt-serial
Нет некорректых ошибок

Fix wrong duplicate MQTT topic error

---

backend/wb/homeui_backend/cert.py

Поменял url для запроса сертификата
Ничего
Заупстил, проверил, что сертификат выдаётся

Add new endpoint

---

debian/changelog
frontend/src/components/checkbox/checkbox.tsx
frontend/src/components/checkbox/index.ts
frontend/src/components/checkbox/styles.css
frontend/src/components/checkbox/types.ts
frontend/src/components/confirm/confirm.tsx
frontend/src/components/confirm/styles.css
frontend/src/components/dialog/dialog.tsx
frontend/src/components/dialog/index.ts
frontend/src/components/dialog/styles.css
frontend/src/components/dialog/types.ts
frontend/src/components/dropdown/dropdown.tsx
frontend/src/components/dropdown/styles.css
frontend/src/components/dropdown/types.ts
frontend/src/components/input/input.tsx
frontend/src/components/input/types.ts

Добавил компоненты из feature/PRJ-643-load-config

Add React components

---

debian/changelog
frontend/src/assets/icons/close.svg
frontend/src/components/button/button.tsx
frontend/src/components/button/styles.css
frontend/src/components/card/styles.css
frontend/src/components/confirm/confirm.tsx
frontend/src/components/dialog/dialog.tsx
frontend/src/components/dialog/styles.css
frontend/src/components/dialog/types.ts
frontend/src/components/dropdown/styles.css
frontend/src/components/tabs/index.ts
frontend/src/components/tabs/styles.css
frontend/src/components/tabs/tabs.tsx
frontend/src/components/tabs/types.ts
frontend/src/components/tabs/use-tabs.ts
frontend/src/components/textarea/index.ts
frontend/src/components/textarea/styles.css
frontend/src/components/textarea/textarea.tsx
frontend/src/components/textarea/types.ts
frontend/src/layouts/page/styles.css

Обновил компоненты, добавил компоненты Tabs и Textarea
локально

react common components update

---

debian/changelog
frontend/src/components/dialog/dialog.tsx

Убрал закрытие диалога по клику вне его. У нас есть отдельная кнопочка для этого
Ничего

Remove closing dialog by clicking outside of it

---

backend/wb/homeui_backend/main.py
debian/changelog

Увеличил время протухания печеньки для админа до 14 дней
Не будет каждый час просить логин

Set admin cookie expiration to 14 days

---

backend/21wb-homeui-backend
debian/changelog

Созраняю базу пользователей между обновлениями фитом

Backup users db in /mnt/data

---

debian/changelog
frontend/app/scripts/app.js

В старых браузерах не работало подключение к mqtt
локально

fix https connection in old browsers
